serviceAccount:
  create: false
  name: ""

ingress:
  enabled: false

replicaCount: 1

image:
  repository: donsasi/node-demo-app
  tag: 1.0
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000

autoscaling:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

podLabels: {}

imagePullSecrets: []

securityContext: {}

volumeMounts: []

volumes: []

livenessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
