name: CI/CD DevOps Demo

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t donsasi/node-demo-app:1.0 ./app

      - name: Push Docker image
        run: docker push donsasi/node-demo-app:1.0

      - name: Set up Kubeconfig
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.0'

      - name: Deploy Helm chart
        run: |
          helm upgrade --install node-demo helm/node-demo-app
