name: CI/CD Pipeline - Node Demo App

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3️⃣ Login to DockerHub
      - name: DockerHub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4️⃣ Build & Push Docker Image
      - name: Build and push Docker image
        run: |
          IMAGE_NAME=donsasi/node-demo-app
          VERSION=${{ github.run_number }}
          docker build -t $IMAGE_NAME:$VERSION .
          docker push $IMAGE_NAME:$VERSION
          echo "IMAGE_TAG=$VERSION" >> $GITHUB_ENV

      # 5️⃣ Update kubeconfig (EKS)
      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name your-cluster-name --region ${{ secrets.AWS_REGION }}

      # 6️⃣ Deploy with Helm
      - name: Helm upgrade/install
        run: |
          NAMESPACE=dev
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            NAMESPACE=prod
          fi

          helm upgrade --install node-demo ./helm/node-demo-app \
            --namespace $NAMESPACE --create-namespace \
            --set image.repository=donsasi/node-demo-app \
            --set image.tag=${{ env.IMAGE_TAG }}
