name: CI/CD DevOps Demo

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # 3️⃣ Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t donsasi/node-demo-app:1.0 ./app

      # 5️⃣ Push Docker image to DockerHub
      - name: Push Docker image
        run: docker push donsasi/node-demo-app:1.0

      # 6️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 7️⃣ Update kubeconfig to connect to EKS
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name devops-demo-cluster

      # 8️⃣ Deploy/Upgrade Helm chart
      - name: Deploy Helm chart
        run: helm upgrade --install node-demo helm/node-demo-app
